require("dotenv").config();
module.exports = {
  test: {
    username: 'root',
    password: 'root',
    database: 'dimitra_livestock_nest',
    host: '127.0.0.1',
    dialect: 'mysql',
  },
  production: {
    username: process.env.LIVE_USERNAME,
    password: process.env.LIVE_PASSWORD,
    database: process.env.LIVE_DB,
    host: process.env.LIVE_HOST,
    // port: process.env.LIVE_PORT || 3306,
    dialect: 'mysql',
    pool: {
      max: 20,
      min: 0,
      acquire: 60000,
      idle: 10000,
    },
    timezone: '+00:00',
  },
  development: {
    dialect: 'mysql',
    host: process.env.HOST || '54.219.140.66',
    port: parseInt(process.env.DB_PORT) || 3306,
    username: process.env.DB_USERNAME || 'master',
    password: process.env.PASSWORD || 'qaWSedRFp;OLikUJ1',
    database: process.env.DATABASE || 'dbdimitra_livestock_farmer_falcon',
    pool: {
      max: 20,
      min: 0,
      acquire: 60000,
      idle: 10000,
    },
  },

  staging: {
    username: process.env.LIVE_USERNAME,
    password: process.env.LIVE_PASSWORD,
    database: process.env.LIVE_DB,
    host: process.env.LIVE_HOST,
    // port: process.env.LIVE_PORT || 3306,
    dialect: 'mysql',
    pool: {
      max: 20,
      min: 0,
      acquire: 60000,
      idle: 10000,
    },
  },
  uat: {
    username: process.env.LIVE_USERNAME,
    password: process.env.LIVE_PASSWORD,
    database: process.env.LIVE_DB,
    host: process.env.LIVE_HOST,
    // port: process.env.LIVE_PORT || 3306,
    dialect: 'mysql',
    pool: {
      max: 20,
      min: 0,
      acquire: 60000,
      idle: 10000,
    },
  },
  local: {
    username: process.env.LOCAL_USERNAME,
    password: process.env.LOCAL_PASSWORD,
    database: process.env.LOCAL_DB,
    host: process.env.LOCAL_HOST,
    port: process.env.LOCAL_PORT || 3306,
    dialect: 'mysql',
    pool: {
      max: parseInt(process.env.MAX_DB_CONNECTION),
      min: parseInt(process.env.MIN_DB_CONNECTION),
      acquire: 60000,
    },
    timezone: '+00:00',
  },
  stagingLive: {
    username: process.env.STAGING_USERNAME,
    password: process.env.STAGING_PASSWORD,
    database: process.env.STAGING_DB,
    host: process.env.STAGING_HOST,
    port: process.env.STAGING_PORT || 3306,
    dialect: 'mysql',
    pool: {
      max: parseInt(process.env.MAX_DB_CONNECTION),
      min: parseInt(process.env.MIN_DB_CONNECTION),
      acquire: 60000,
    },
    timezone: '+00:00',
  },
  amitlocal: {
    dialect: 'mysql',
    host: 'localhost',
    port: 3306,
    username: 'root',
    password: 'root',
    database: 'dbdimitra_livestock_sync',
  },
};
