const COUNTRIES: { code: string; name: string; code3: string; continentCode: string; continentName: string; alternativeNames?: string[] }[] = [
  {
    code: 'AF',
    code3: 'AFG',
    name: 'Afghanistan',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'AX',
    code3: 'ALD',
    name: 'Aland',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'AL',
    code3: 'ALB',
    name: 'Albania',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'DZ',
    code3: 'DZA',
    name: 'Algeria',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'AS',
    code3: 'ASM',
    name: 'American Samoa',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'AD',
    code3: 'AND',
    name: 'Andorra',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'AO',
    code3: 'AGO',
    name: 'Angola',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'AI',
    code3: 'AIA',
    name: 'Anguilla',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'AQ',
    code3: 'ATA',
    name: 'Antarctica',
    continentCode: 'AN',
    continentName: 'Antarctica',
  },
  {
    code: 'AG',
    code3: 'ATG',
    name: 'Antigua and Barbuda',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'AR',
    code3: 'ARG',
    name: 'Argentina',
    continentCode: 'SA',
    continentName: 'South America',
  },
  {
    code: 'AM',
    code3: 'ARM',
    name: 'Armenia',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'AW',
    code3: 'ABW',
    name: 'Aruba',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'AU',
    code3: 'AUS',
    name: 'Australia',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'AT',
    code3: 'AUT',
    name: 'Austria',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'AZ',
    code3: 'AZE',
    name: 'Azerbaijan',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'BH',
    code3: 'BHR',
    name: 'Bahrain',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'BD',
    code3: 'BGD',
    name: 'Bangladesh',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'BB',
    code3: 'BRB',
    name: 'Barbados',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'BY',
    code3: 'BLR',
    name: 'Belarus',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'BE',
    code3: 'BEL',
    name: 'Belgium',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'BZ',
    code3: 'BLZ',
    name: 'Belize',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'BJ',
    code3: 'BEN',
    name: 'Benin',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'BM',
    code3: 'BMU',
    name: 'Bermuda',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'BT',
    code3: 'BTN',
    name: 'Bhutan',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'BO',
    code3: 'BOL',
    name: 'Bolivia',
    continentCode: 'SA',
    continentName: 'South America',
  },
  {
    code: 'BA',
    code3: 'BIH',
    name: 'Bosnia and Herzegovina',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'BW',
    code3: 'BWA',
    name: 'Botswana',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'BR',
    code3: 'BRA',
    name: 'Brazil',
    continentCode: 'SA',
    continentName: 'South America',
  },
  {
    code: 'IO',
    code3: 'IOT',
    name: 'British Indian Ocean Territory',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'VG',
    code3: 'VGB',
    name: 'British Virgin Islands',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'BN',
    code3: 'BRN',
    name: 'Brunei',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'BG',
    code3: 'BGR',
    name: 'Bulgaria',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'BF',
    code3: 'BFA',
    name: 'Burkina Faso',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'BI',
    code3: 'BDI',
    name: 'Burundi',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'KH',
    code3: 'KHM',
    name: 'Cambodia',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'CM',
    code3: 'CMR',
    name: 'Cameroon',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'CA',
    code3: 'CAN',
    name: 'Canada',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'CV',
    code3: 'CPV',
    name: 'Cape Verde',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'KY',
    code3: 'CYM',
    name: 'Cayman Islands',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'CF',
    code3: 'CAF',
    name: 'Central African Republic',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'TD',
    code3: 'TCD',
    name: 'Chad',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'CL',
    code3: 'CHL',
    name: 'Chile',
    continentCode: 'SA',
    continentName: 'South America',
  },
  {
    code: 'CN',
    code3: 'CHN',
    name: 'China',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'CO',
    code3: 'COL',
    name: 'Colombia',
    continentCode: 'SA',
    continentName: 'South America',
  },
  {
    code: 'KM',
    code3: 'COM',
    name: 'Comoros',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'CK',
    code3: 'COK',
    name: 'Cook Islands',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'CR',
    code3: 'CRI',
    name: 'Costa Rica',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'HR',
    code3: 'HRV',
    name: 'Croatia',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'CW',
    code3: 'CUW',
    name: 'Curaçao',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'CZ',
    code3: 'CZE',
    name: 'Czech Republic',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'CD',
    code3: 'COD',
    name: 'Democratic Republic of the Congo',
    alternativeNames: ['DR Congo', 'DRC', 'Congo-Kinshasa'],
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'DK',
    code3: 'DNK',
    name: 'Denmark',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'CY',
    code3: 'ESB',
    name: 'Dhekelia Sovereign Base Area',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'DJ',
    code3: 'DJI',
    name: 'Djibouti',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'DM',
    code3: 'DMA',
    name: 'Dominica',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'DO',
    code3: 'DOM',
    name: 'Dominican Republic',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'TL',
    code3: 'TLS',
    name: 'East Timor',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'EC',
    code3: 'ECU',
    name: 'Ecuador',
    continentCode: 'SA',
    continentName: 'South America',
  },
  {
    code: 'EG',
    code3: 'EGY',
    name: 'Egypt',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'SV',
    code3: 'SLV',
    name: 'El Salvador',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'GQ',
    code3: 'GNQ',
    name: 'Equatorial Guinea',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'ER',
    code3: 'ERI',
    name: 'Eritrea',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'EE',
    code3: 'EST',
    name: 'Estonia',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'ET',
    code3: 'ETH',
    name: 'Ethiopia',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'FK',
    code3: 'FLK',
    name: 'Falkland Islands',
    continentCode: 'SA',
    continentName: 'South America',
  },
  {
    code: 'FO',
    code3: 'FRO',
    name: 'Faroe Islands',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'FM',
    code3: 'FSM',
    name: 'Federated States of Micronesia',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'FJ',
    code3: 'FJI',
    name: 'Fiji',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'FI',
    code3: 'FIN',
    name: 'Finland',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'FR',
    code3: 'FRA',
    name: 'France',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'PF',
    code3: 'PYF',
    name: 'French Polynesia',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'TF',
    code3: 'ATF',
    name: 'French Southern and Antarctic Lands',
    continentCode: 'AN',
    continentName: 'Antarctica',
  },
  {
    code: 'GA',
    code3: 'GAB',
    name: 'Gabon',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'GM',
    code3: 'GMB',
    name: 'Gambia',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'PS',
    code3: 'PSX',
    name: 'Gaza Strip',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'GE',
    code3: 'GEO',
    name: 'Georgia',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'DE',
    code3: 'DEU',
    name: 'Germany',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'GH',
    code3: 'GHA',
    name: 'Ghana',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'GI',
    code3: 'GIB',
    name: 'Gibraltar',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'GR',
    code3: 'GRC',
    name: 'Greece',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'GL',
    code3: 'GRL',
    name: 'Greenland',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'GD',
    code3: 'GRD',
    name: 'Grenada',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'GU',
    code3: 'GUM',
    name: 'Guam',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'GT',
    code3: 'GTM',
    name: 'Guatemala',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'GG',
    code3: 'GGY',
    name: 'Guernsey',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'GN',
    code3: 'GIN',
    name: 'Guinea',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'GW',
    code3: 'GNB',
    name: 'Guinea Bissau',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'GY',
    code3: 'GUY',
    name: 'Guyana',
    continentCode: 'SA',
    continentName: 'South America',
  },
  {
    code: 'HT',
    code3: 'HTI',
    name: 'Haiti',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'HM',
    code3: 'HMD',
    name: 'Heard Island and McDonald Islands',
    continentCode: 'AN',
    continentName: 'Antarctica',
  },
  {
    code: 'HN',
    code3: 'HND',
    name: 'Honduras',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'HK',
    code3: 'HKG',
    name: 'Hong Kong S.A.R.',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'HU',
    code3: 'HUN',
    name: 'Hungary',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'IS',
    code3: 'ISL',
    name: 'Iceland',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'IN',
    code3: 'IND',
    name: 'India',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'ID',
    code3: 'IDN',
    name: 'Indonesia',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'IR',
    code3: 'IRN',
    name: 'Iran',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'IQ',
    code3: 'IRQ',
    name: 'Iraq',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'IE',
    code3: 'IRL',
    name: 'Ireland',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'IM',
    code3: 'IMN',
    name: 'Isle of Man',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'IL',
    code3: 'ISR',
    name: 'Israel',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'IT',
    code3: 'ITA',
    name: 'Italy',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'CI',
    code3: 'CIV',
    name: 'Ivory Coast',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'JM',
    code3: 'JAM',
    name: 'Jamaica',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'JP',
    code3: 'JPN',
    name: 'Japan',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'JE',
    code3: 'JEY',
    name: 'Jersey',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'JO',
    code3: 'JOR',
    name: 'Jordan',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'KZ',
    code3: 'KAZ',
    name: 'Kazakhstan',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'KE',
    code3: 'KEN',
    name: 'Kenya',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'KI',
    code3: 'KIR',
    name: 'Kiribati',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'XK',
    code3: 'KOS',
    name: 'Kosovo',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'KW',
    code3: 'KWT',
    name: 'Kuwait',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'KG',
    code3: 'KGZ',
    name: 'Kyrgyzstan',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'LA',
    code3: 'LAO',
    name: 'Laos',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'LV',
    code3: 'LVA',
    name: 'Latvia',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'LB',
    code3: 'LBN',
    name: 'Lebanon',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'LS',
    code3: 'LSO',
    name: 'Lesotho',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'LR',
    code3: 'LBR',
    name: 'Liberia',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'LY',
    code3: 'LBY',
    name: 'Libya',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'LI',
    code3: 'LIE',
    name: 'Liechtenstein',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'LT',
    code3: 'LTU',
    name: 'Lithuania',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'LU',
    code3: 'LUX',
    name: 'Luxembourg',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'MO',
    code3: 'MAC',
    name: 'Macau S.A.R',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'MK',
    code3: 'MKD',
    name: 'Macedonia',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'MG',
    code3: 'MDG',
    name: 'Madagascar',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'MW',
    code3: 'MWI',
    name: 'Malawi',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'MY',
    code3: 'MYS',
    name: 'Malaysia',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'MV',
    code3: 'MDV',
    name: 'Maldives',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'ML',
    code3: 'MLI',
    name: 'Mali',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'MT',
    code3: 'MLT',
    name: 'Malta',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'MH',
    code3: 'MHL',
    name: 'Marshall Islands',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'MR',
    code3: 'MRT',
    name: 'Mauritania',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'MU',
    code3: 'MUS',
    name: 'Mauritius',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'MX',
    code3: 'MEX',
    name: 'Mexico',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'MD',
    code3: 'MDA',
    name: 'Moldova',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'MC',
    code3: 'MCO',
    name: 'Monaco',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'MN',
    code3: 'MNG',
    name: 'Mongolia',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'ME',
    code3: 'MNE',
    name: 'Montenegro',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'MS',
    code3: 'MSR',
    name: 'Montserrat',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'MA',
    code3: 'MAR',
    name: 'Morocco',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'MZ',
    code3: 'MOZ',
    name: 'Mozambique',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'MM',
    code3: 'MMR',
    name: 'Myanmar',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'NA',
    code3: 'NAM',
    name: 'Namibia',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'NR',
    code3: 'NRU',
    name: 'Nauru',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'NP',
    code3: 'NPL',
    name: 'Nepal',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'NL',
    code3: 'NLD',
    name: 'Netherlands',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'NC',
    code3: 'NCL',
    name: 'New Caledonia',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'NZ',
    code3: 'NZL',
    name: 'New Zealand',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'NI',
    code3: 'NIC',
    name: 'Nicaragua',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'NE',
    code3: 'NER',
    name: 'Niger',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'NG',
    code3: 'NGA',
    name: 'Nigeria',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'NU',
    code3: 'NIU',
    name: 'Niue',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'NF',
    code3: 'NFK',
    name: 'Norfolk Island',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'KP',
    code3: 'PRK',
    name: 'North Korea',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'MP',
    code3: 'MNP',
    name: 'Northern Mariana Islands',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'NO',
    code3: 'NOR',
    name: 'Norway',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'OM',
    code3: 'OMN',
    name: 'Oman',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'PK',
    code3: 'PAK',
    name: 'Pakistan',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'PW',
    code3: 'PLW',
    name: 'Palau',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'PA',
    code3: 'PAN',
    name: 'Panama',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'PG',
    code3: 'PNG',
    name: 'Papua New Guinea',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'PY',
    code3: 'PRY',
    name: 'Paraguay',
    continentCode: 'SA',
    continentName: 'South America',
  },
  {
    code: 'PE',
    code3: 'PER',
    name: 'Peru',
    continentCode: 'SA',
    continentName: 'South America',
  },
  {
    code: 'PH',
    code3: 'PHL',
    name: 'Philippines',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'PN',
    code3: 'PCN',
    name: 'Pitcairn Islands',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'PL',
    code3: 'POL',
    name: 'Poland',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'PT',
    code3: 'PRT',
    name: 'Portugal',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'PR',
    code3: 'PRI',
    name: 'Puerto Rico',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'QA',
    code3: 'QAT',
    name: 'Qatar',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'RS',
    code3: 'SRB',
    name: 'Republic of Serbia',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'CG',
    code3: 'COG',
    name: 'Republic of the Congo',
    alternativeNames: ['Congo-Brazzaville', 'Congo'],
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'RO',
    code3: 'ROU',
    name: 'Romania',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'RU',
    code3: 'RUS',
    name: 'Russia',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'RW',
    code3: 'RWA',
    name: 'Rwanda',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'SS',
    code3: 'SDS',
    name: 'S. Sudan',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'BL',
    code3: 'BLM',
    name: 'Saint Barthelemy',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'SH',
    code3: 'SHN',
    name: 'Saint Helena',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'KN',
    code3: 'KNA',
    name: 'Saint Kitts and Nevis',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'LC',
    code3: 'LCA',
    name: 'Saint Lucia',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'MF',
    code3: 'MAF',
    name: 'Saint Martin',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'PM',
    code3: 'SPM',
    name: 'Saint Pierre and Miquelon',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'VC',
    code3: 'VCT',
    name: 'Saint Vincent and the Grenadines',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'WS',
    code3: 'WSM',
    name: 'Samoa',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'SM',
    code3: 'SMR',
    name: 'San Marino',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'ST',
    code3: 'STP',
    name: 'Sao Tome and Principe',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'SA',
    code3: 'SAU',
    name: 'Saudi Arabia',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'SN',
    code3: 'SEN',
    name: 'Senegal',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'SC',
    code3: 'SYC',
    name: 'Seychelles',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'SL',
    code3: 'SLE',
    name: 'Sierra Leone',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'SG',
    code3: 'SGP',
    name: 'Singapore',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'SX',
    code3: 'SXM',
    name: 'Sint Maarten',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'SK',
    code3: 'SVK',
    name: 'Slovakia',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'SI',
    code3: 'SVN',
    name: 'Slovenia',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'SB',
    code3: 'SLB',
    name: 'Solomon Islands',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'SO',
    code3: 'SOM',
    name: 'Somalia',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'ZA',
    code3: 'ZAF',
    name: 'South Africa',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'GS',
    code3: 'SGS',
    name: 'South Georgia and the Islands',
    continentCode: 'AN',
    continentName: 'Antarctica',
  },
  {
    code: 'KR',
    code3: 'KOR',
    name: 'South Korea',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'ES',
    code3: 'ESP',
    name: 'Spain',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'LK',
    code3: 'LKA',
    name: 'Sri Lanka',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'SD',
    code3: 'SDN',
    name: 'Sudan',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'SR',
    code3: 'SUR',
    name: 'Suriname',
    continentCode: 'SA',
    continentName: 'South America',
  },
  {
    code: 'SZ',
    code3: 'SWZ',
    name: 'Swaziland',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'SE',
    code3: 'SWE',
    name: 'Sweden',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'CH',
    code3: 'CHE',
    name: 'Switzerland',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'SY',
    code3: 'SYR',
    name: 'Syria',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'TW',
    code3: 'TWN',
    name: 'Taiwan',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'TJ',
    code3: 'TJK',
    name: 'Tajikistan',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'TH',
    code3: 'THA',
    name: 'Thailand',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'BS',
    code3: 'BHS',
    name: 'The Bahamas',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'TG',
    code3: 'TGO',
    name: 'Togo',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'TK',
    code3: 'TKL',
    name: 'Tokelau',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'TO',
    code3: 'TON',
    name: 'Tonga',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'TT',
    code3: 'TTO',
    name: 'Trinidad and Tobago',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'TN',
    code3: 'TUN',
    name: 'Tunisia',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'TR',
    code3: 'TUR',
    name: 'Turkey',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'TM',
    code3: 'TKM',
    name: 'Turkmenistan',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'TC',
    code3: 'TCA',
    name: 'Turks and Caicos Islands',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'TV',
    code3: 'TUV',
    name: 'Tuvalu',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'UG',
    code3: 'UGA',
    name: 'Uganda',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'UA',
    code3: 'UKR',
    name: 'Ukraine',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'AE',
    code3: 'ARE',
    name: 'United Arab Emirates',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'GB',
    code3: 'GBR',
    name: 'United Kingdom',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'TZ',
    code3: 'TZA',
    name: 'United Republic of Tanzania',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'UM',
    code3: 'UMI',
    name: 'United States Minor Outlying Islands',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'US',
    code3: 'USA',
    name: 'United States of America',
    alternativeNames: ['United States', 'America'],
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'VI',
    code3: 'VIR',
    name: 'United States Virgin Islands',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'UY',
    code3: 'URY',
    name: 'Uruguay',
    continentCode: 'SA',
    continentName: 'South America',
  },
  {
    code: 'CU',
    code3: 'USG',
    name: 'US Naval Base Guantanamo Bay',
    continentCode: 'NA',
    continentName: 'North America',
  },
  {
    code: 'UZ',
    code3: 'UZB',
    name: 'Uzbekistan',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'VU',
    code3: 'VUT',
    name: 'Vanuatu',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'VA',
    code3: 'VAT',
    name: 'Vatican',
    continentCode: 'EU',
    continentName: 'Europe',
  },
  {
    code: 'VE',
    code3: 'VEN',
    name: 'Venezuela',
    continentCode: 'SA',
    continentName: 'South America',
  },
  {
    code: 'VN',
    code3: 'VNM',
    name: 'Vietnam',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'WF',
    code3: 'WLF',
    name: 'Wallis and Futuna',
    continentCode: 'OC',
    continentName: 'Oceania',
  },
  {
    code: 'EH',
    code3: 'SAH',
    name: 'Western Sahara',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'YE',
    code3: 'YEM',
    name: 'Yemen',
    continentCode: 'AS',
    continentName: 'Asia',
  },
  {
    code: 'ZM',
    code3: 'ZMB',
    name: 'Zambia',
    continentCode: 'AF',
    continentName: 'Africa',
  },
  {
    code: 'ZW',
    code3: 'ZWE',
    name: 'Zimbabwe',
    continentCode: 'AF',
    continentName: 'Africa',
  },
];
export default COUNTRIES;
